version: "3.8"
services:
  campaign_service_db: 
    image: postgres:latest
    container_name: campaign_service_postgres 
    restart: always
    env_file:
      - ./.env.dev


  campaign_service: 
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env.dev
    depends_on:
      - campaign_service_db 
    volumes:
    - ./coverage_reports:/work/coverage_reports
    