version: "3.8"

networks:
  apigateway_system_network:
    external: true

services:
  campaign_service: # TODO
    volumes:
      - ./postgres-data:/var/lib/postgresql
    env_file:
      - ./.env.prod
    hostname:
      campaign_service # TODO
    networks:
      - apigateway_system_network
  
  campaign_service_db:
    env_file:
      - ./.env.prod
    hostname:
      campaign_service_db # TODO
    networks:
      - apigateway_system_network